### ISSUE TITLE
Arreglar lectura y escritura de ficheros de objetos

### ISSUE THREAD

**Issue by PSanchezR** [PSanchezR/Camino#1]
Hace falta arreglar la escritura y lectura de objetos usuario de un fichero de objetos del mismo tipo.

**Comment by germaaan** [comment]
El problema para guardar el objeto "usuario" en el archivo estaba en que es la clase Usuario la que tiene que implementar la interfaz Serializable no la clase del formulario. Además se tienen que usar FileOutputStream y ObjectOutputStream.
