### ISSUE TITLE
Problema clase gestion ficheros

### ISSUE THREAD

**Issue by PSanchezR** [PSanchezR/Camino#4]
He querido centralizar todo el acceso a ficheros dentro de una clase para así poder utilizarlo desde toda la app sin necesidad de reescribir código, el problema viene cuando quiero utilizar esta clase en los activities formulario_nuevo_usuario y seleccion_usuario, que da un fallo de NullPointerException y se sale la app.

**Comment by germaaan** [comment]
El problema estaba en que para llamar la función desde una clase externa a la actividad tiene que conocer su contexto por lo que hay que pasárselo a la función en cuestión con el método `getBaseContext()`.

**Comment by germaaan** [comment]
Reabro hasta que solucione el tema de la excepción del flujo de lectura de objetos.

**Comment by PSanchezR** [comment]
Correcto, lo he cerrado antes de tiempo!!

**Comment by germaaan** [comment]
No problem.
